### ISSUE TITLE
Segmentation fault when trying to duplicate the track

### ISSUE THREAD

**Issue by iurienistor** [Yoshimi/yoshimi#121] opened 2020-12-21 20:16 UTC
When I am trying to duplicate the track in Ardour I am getting segmentation fault in Yoshimi (version 1.7.3). For me is reproducible 100% of the cases.

#0  0x00007f8253107d35 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    at /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007f825310812e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    at /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f820a4668e1 in InterChange::generateSpecialInstrument(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (this=0x55d682405a60, npart=0, name="First Instrument")
    at /home/iurie/projects/yoshimi-1.7.3/src/Interface/InterChange.cpp:1603
#3  0x00007f820a3d4d3a in Bank::generateSingleRoot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) (this=0x55d6824059f8, newRoot="yoshimi/banks", clear=true)
    at /home/iurie/projects/yoshimi-1.7.3/src/Misc/Bank.cpp:1209
#4  0x00007f820a3d6865 in Bank::parseBanksFile(XMLwrapper*) (this=0x55d6824059f8, xml=0x0) at /home/iurie/projects/yoshimi-1.7.3/src/Misc/Bank.cpp:1507
#5  0x00007f820a414e1c in SynthEngine::installBanks() (this=0x55d6824059f0) at /home/iurie/projects/yoshimi-1.7.3/src/Misc/SynthEngine.cpp:2425
#6  0x00007f820a3ae863 in YoshimiLV2Plugin::instantiate(_LV2_Descriptor const*, double, char const*, _LV2_Feature const* const*)
    (desc=0x7f820a613960 <yoshimi_lv2_desc>, sample_rate=44100, bundle_path=0x55d6823f0b40 "/usr/local/lib/lv2/yoshimi.lv2/", features=0x55d6823b08c0)
    at /home/iurie/projects/yoshimi-1.7.3/src/LV2_Plugin/YoshimiLV2Plugin.cpp:397
#7  0x00007f82532f1623 in lilv_plugin_instantiate () at /lib/x86_64-linux-gnu/liblilv-0.so.0
#8  0x00007f82568594dc in ARDOUR::LV2Plugin::init(void const*, long) (this=0x55d6823823e0, c_plugin=0x55d66b2c8780, rate=44100) at ../libs/ardour/lv2_plugin.cc:631
#9  0x00007f8256857d19 in ARDOUR::LV2Plugin::LV2Plugin(ARDOUR::AudioEngine&, ARDOUR::Session&, void const*, long) (this=0x55d6823823e0, engine=..., session=..., c_plugin=0x55d66b2c8780, rate=44100)

**Comment by abrolag** [comment] 2020-12-21 21:16
Currently not able to reproduce this here. That's with Ardour version 6.0
What version are you using?
I'm also very unfamiliar with Ardour so it's possible I'm making the duplication in a non-standard way.

**Comment by iurienistor** [comment] 2020-12-22 13:35
@abrolag Ardour 6.5. I'll try to investigate more on this.

**Comment by iurienistor** [comment] 2020-12-22 15:49
@abrolag Sorry, I have forgot to set the maximum locked memory. Now it is ok.

**Comment by iurienistor** [comment] 2020-12-22 17:07
I have made a pull request and comment there about the issue. I was wrong memory lock limit settings wasn't the problem.

**Comment by abrolag** [comment] 2020-12-22 19:23
On Tue, 22 Dec 2020 05:35:38 -0800
Iurie Nistor <notifications@github.com> wrote:

>@abrolag Ardour 6.5. I'll try to investigate more on this.
>
Thinking further on this, while obviously if the initialisation had failed, we
shouldn't have been continuing with banks etc. but what caused it to fail?
Yoshimi does send quite a lot of info to stderr on failures, but I don't know
where Ardour reports this, or even if it does. Without the segfault this may
appear.

Presumably under these circumstances the track data would be duplicated but
with no instance opened.

-- 
Will J Godfrey
http://www.musically.me.uk
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by iurienistor** [comment] 2020-12-22 19:29
@abrolag I think there is e need to investigate because the commit fixes the crash, but creates another problem. This time when duplicating, it will not show any instruments banks in the UI, only the "New Instrument" one.

**Comment by abrolag** [comment] 2020-12-22 20:06
OK I've reopened this. it seems one fault was hiding another :(
Since we reorganised the bank structure it seems that while the first instance finds a full set, secondary instances fail to load any. This is odd, because they should all point to the same set of banks. Is that the same as what you are seeing?

**Comment by abrolag** [comment] 2020-12-23 15:05
OK, I've found one pretty obvious problem. Only the first synth was able to find the local directory where all the bank data is stored!
I'll push a fix for this today.
There is also a lesser problem where if it has to hunt for a bank at startup (because the original one was missing) it finds one, but fails to update the GUI. Still looking for that :(

**Comment by iurienistor** [comment] 2020-12-24 08:27
I have tested from with the latest commits from the master and the banks are found ok, and there is no crash too. I think this issue can be closed.

**Comment by abrolag** [comment] 2020-12-24 14:36
OK, closing now

**Closed by abrolag** 2020-12-24 14:36 UTC
