### ISSUE TITLE
Yoshimi's GUI doesn't shows up when launched with jalv

### ISSUE THREAD

**Issue by trebmuh** [Yoshimi/yoshimi#42] opened 2017-12-30 19:33 UTC
When launched (Yoshimi 1.5.6) as a LV2 within Ardour (5.12) or Qtractor (0.8.5), the GUI is showing up fine. When launched as a standalone app, it's fine as well.

But when launched with jalv, jalv.gtk, jalv.gtk3, or jalv.qt5, there is no GUI but a simple "freewheel" tickbox.

I'm not too sure if that's supposed to be the case or not. Could you please tell me?

With jalv.gtk
![yoshimi-jalvgtk](https://user-images.githubusercontent.com/8705846/34456848-1fbd9e16-eda1-11e7-8dc4-afd6335931a8.png)

With jalv.qt5
![yoshimi-jalvqt5](https://user-images.githubusercontent.com/8705846/34456852-2d846b88-eda1-11e7-9d4c-76251a5a56cd.png)

**Comment by abrolag** [comment] 2017-12-30 19:57
On Sat, 30 Dec 2017 19:33:30 +0000 (UTC)
Olivier Humbert <notifications@github.com> wrote:

>When launched as a LV2 within Ardour (5.12) or Qtractor (0.8.5), the GUI is showing up fine. When launched as a standalone app, it's fine as well.
>
>But when launched with jalv, jalv.gtk, jalv.gtk3, or jalv.qt5, there is no GUI but a simple "freewheel" tickbox.
>
>I'm not too sure if that's supposed to be the case or not. Could you please tell me?
>Yoshimi 1.5.6
>
>
I don't think we've ever looked at jalv.

Why would you want to run Yoshimi in it? As far as I understand it simply turns
LV2 plugins into stand-alone programs, which Yoshimi already is!

Is there something special you are doing?

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by trebmuh** [comment] 2017-12-30 21:31
> Why would you want to run Yoshimi in it? As far as I understand it simply turns LV2 plugins into stand-alone programs, which Yoshimi already is!
> 
> Is there something special you are doing?

Not really, that's just that I've jalv.select (which is a GUI for jalv) always launched in my systray and it's faster for me to launch it from here rather than launching from the menu or CLI.

**Comment by abrolag** [comment] 2018-01-01 19:19
Ok, well I'll leave this for now. it's not really a high priority, and I'm not exactly short of other things to work on :(

Incidentally, I run with qjackctl, having it auto start jackd on startup. In options I use 'Execute script after Startup' to call Yoshimi. That way, it's ready for anything else that may want to connect to it.

**Comment by trebmuh** [comment] 2018-01-03 16:50
Up to you.

Just adding that [jalv](https://github.com/drobilla/jalv) being the lv2 reference host, it sounds like a reasonable guess that a Yoshimi LV2 working properly in jalv would probably help yoshimi to work in the bunch of LV2 host application out there.

Unfortunately, I'm not a programmer so I can't help much more than reporting it doesn't work (yet) in jalv.

Anyway, all the best to you and best wishes to you and yours for 2018.

**Comment by abrolag** [comment] 2018-01-03 17:07
Thanks for the additional info. I'm not an LV2 user at all, and was not aware of this.
The developer who programmed Yoshimi's LV2 interface is currently highly involved in other things, and at the moment I don't know anyone who can help. However I won't close this, and I'll also ask around to see what we can come up with.

Happy New Year to you and yours as well :)

**Comment by dbtx** [comment] 2018-01-07 21:35
Hi,
I haven't looked in Qtractor but I have compared jalv with Ardour... one big difference is that jalv necessarily uses suil (to be able to load plugin UIs which use other GUI toolkits), while apparently Ardour can work with or without it [as seen here](https://github.com/Ardour/ardour/blob/master/libs/ardour/lv2_plugin.cc#L820)-- a tad bit more complex than jalv's init. The Qtractor site likewise lists suil as an optional dependency. Whether or not it actually matters, suil doesn't know anything about FLTK. But jalv's (and suil's, etc) original author apparently also wrote Ardour's LV2 support, so it seems the problem is better stated as a jalv feature request. I'm still trying to figure out how openAV plugins with OpenGL UIs on top of AVTK also work with jalv.gtk-- I guess it's suil's x11 support, and I guess I'm in up to my nostrils ;)

**Comment by abrolag** [comment] 2018-01-07 21:48
I can confirm that both Qtractor and MusE have no problem with Yoshimi's GUI.
However, only MusE seems to *auto* open the GUI.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by trebmuh** [comment] 2018-08-10 12:31
Still th same with 1.5.8.2

**Comment by abrolag** [comment] 2018-08-10 13:13
This is still on my personal watch list, although as dbtx suggested it is really an issue with suil, which jalv depends on. This is the problem with cascading dependencies making it very hard for top level programs to find work-rounds.

If you look here: https://drobilla.net/software/suil
you'll see the mention gtk, qt and x11 directly and none others. They refer to 'supported' toolkits, but nowhere can i find a list of these.

I thought I'd already contacted the suil developers and got no reply. However, I've just tried again.

**Comment by danvd** [comment] 2018-08-11 19:26
Hi everyone!

Some words to demystify Yoshimi lv2 + jalv cooperation.  Unlkely that both can work together in terms of UI because:
1). Yoshimi's side: to be compatible with jalv lv2, UI must be must be implemented using one of the list of officially supported UI frontends. They are here: http://lv2plug.in/ns/extensions/ui/. Unfortunately there is no FLTK there. 
2). Jalv's side: to run Yoshimi's UI it must support unofficial  'External UI' extension (we are using http://kxstudio.linuxaudio.org/ns/lv2ext/external-ui#Widget).

2) is unlikely, and 1) is rather complicated task leading to a possible rewrite. 

Honestly I don't understand why the official standard prefers dealing with lots of different UI toolkits instead of using event-based external-ui. The latter just hides implementation from the host.

So...

**Comment by abrolag** [comment] 2018-08-11 20:14
Thanks a lot Andrew. That does clarify things a lot. What's more it turns out that none other than Robin Gareus has written a patch for Jalv that does in fact enable it to use this extension :)
It is available here: http://kxstudio.linuxaudio.org/ns/lv2ext/jalv_extui_svn5273b.diff
So now, if anyone is building Jalv from source they can apply it.

I'm seriously considering including a copy in Yoshimi's code as extra 'insurance'

**Comment by abrolag** [comment] 2018-08-12 08:40
With Andrews comments, and information I now have from one of the jalv devs I have a clearer understanding of the issue.

The extension that Yoshimi relies on was written by Filipe Coelho who is generally recognised as an authority on LV2. The LV2 spec *specifically* allows extensions and this one precisely follows all the requirements. It is quite widely used and in fact is recognised by Ardour, MusE, qtractor and carla.

However, there is no requirement for any LV2 host to recognise these extensions, and Jalv (as the reference) only supports the basic LV2 spec. For whatever reason, there seems to be no likelihood of this getting included in the spec, and I don't think it's reasonable for us to do a significant re-write for so little benefit, therefore I can't see a way forward.

I'll leave this open for now, to give everyone the opportunity to comment, but will eventually close it.

**Closed** 2018-08-29 13:35 UTC
